# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Stop IIS Web Service
      run: Stop-Service "GreenCycleIISWebService"
      shell: powershell
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -o built
    - name: Deploy files to IIS Server
      run: |
        # Đảm bảo thư mục đích tồn tại và không có các file cũ
        if (!(Test-Path -Path "C:\inetpub\wwwroot\greencycle")) {
          New-Item -ItemType Directory -Force -Path "C:\inetpub\wwwroot\greencycle"
        }
        else {
          Remove-Item -Path "C:\inetpub\wwwroot\greencycle\*" -Recurse -Force
        }
        
        # Sao chép toàn bộ nội dung từ thư mục built mà không copy thư mục chính
        Copy-Item -Path "built\*" -Destination "C:\inetpub\wwwroot\greencycle" -Recurse -Force
      shell: powershell
    - name: Add URL Rewrite Rules
      run: |
        Import-Module WebAdministration
        # Đường dẫn đến cấu hình IIS cho site
        $configPath = "MACHINE/WEBROOT/APPHOST/greencycle.btecit.tech"
        
        # Lấy danh sách hiện tại của các rules
        $rulesCollection = Get-WebConfigurationProperty -pspath $configPath -filter "system.webServer/rewrite/rules" -name "Collection"
        
        # Kiểm tra nếu rule đã tồn tại, nếu chưa thì thêm mới
        $ruleExists = $rulesCollection | Where-Object { $_.Name -eq "MyRewriteRule" }
        if (-not $ruleExists) {
            # Tạo một rule mới và cấu hình các thuộc tính của nó
            $newRule = New-Object psobject -Property @{
                Name           = "MyRewriteRule";
                StopProcessing = $true
            }
            $newRule | Add-Member -MemberType NoteProperty -Name "Match" -Value (New-Object psobject -Property @{
                Url = "^old-path$"
            })
            $newRule | Add-Member -MemberType NoteProperty -Name "Action" -Value (New-Object psobject -Property @{
                Type         = "Redirect";
                Url          = "/new-path";
                RedirectType = "Permanent"
            })
        
            # Thêm rule vào collection
            $rulesCollection.Add($newRule)
            Set-WebConfigurationProperty -pspath $configPath -filter "system.webServer/rewrite/rules" -name "Collection" -value $rulesCollection
        }
      shell: powershell
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Start Kestrel Service
      run: Start-Service "GreenCycleIISWebService"
    - name: Recycle IIS Application Pool
      run: |
        Import-Module WebAdministration
        Restart-WebAppPool -Name "greencycle.btecit.tech"
      shell: powershell

