# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clean up .github directory
      run: |
        $path = "$GITHUB_WORKSPACE/.github"
        if (Test-Path -Path $path) { Remove-Item -Path $path -Force -Recurse } else { Write-Host "Path not found: $path" }
      shell: pwsh
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ; Stop-Service "GreenCycleIISWebService"
    - name: Build
      run: dotnet publish -c Release -o built
    - name: Deploy files to IIS Server
      run: |
          # Tạo thư mục đích nếu chưa tồn tại
          if (!(Test-Path -Path "C:\inetpub\wwwroot\greencycle.btecit.tech")) {
            New-Item -ItemType Directory -Force -Path "C:\inetpub\wwwroot\greencycle.btecit.tech"
          }

          # Xóa toàn bộ nội dung trong thư mục đích, trừ web.config
          Get-ChildItem -Path "C:\inetpub\wwwroot\greencycle.btecit.tech" -Exclude "web.config", "appsettings.json" | Remove-Item -Recurse -Force

          # Sao chép các file từ thư mục build vào thư mục đích mà không ghi đè web.config
          Copy-Item -Path "built\*" -Destination "C:\inetpub\wwwroot\greencycle.btecit.tech" -Recurse -Force -Exclude "web.config", "appsettings.json"
      shell: powershell
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Start IIS Web Project Service
      run: Start-Service "GreenCycleIISWebService"
    - name: Recycle IIS Application Pool
      run: |
        Import-Module WebAdministration
        Restart-WebAppPool -Name "greencycle.btecit.tech"
      shell: powershell
