# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Stop Kestrel Service
      run: |
          Stop-Service -Name "GreenCycleService"
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release -o built
    - name: Deploy files to IIS Server
      run: |
        # Copy các file đã build đến thư mục deploy trên server
        Copy-Item -Path "built\*" -Destination "C:\inetpub\wwwroot\greencyle" -Recurse -Force
      shell: powershell
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Restart Kestrel Service
      run: |
          Stop-Service -Name "GreenCycleService"
          Start-Service -Name "GreenCycleService"
    - name: Recycle IIS Application Pool
      run: |
        Import-Module WebAdministration
        Restart-WebAppPool -Name "greencycle.btecit.tech"
      shell: powershell

